function isTrue()
	EXPECT_TRUE( 0 )
	ASSERT_TRUE( 0 )
	EXPECT_TRUE( "false" )
	ASSERT_TRUE( "false" )
	EXPECT_FATAL_FAILURE( "BasicTests%.lua(.+)Expected: true(.+)Actual: nil", function()
		ASSERT_TRUE( nil )
	end )
	EXPECT_FATAL_FAILURE( "BasicTests%.lua(.+)Expected: true(.+)Actual: false", function()
		ASSERT_TRUE( false )
	end )
	EXPECT_NONFATAL_FAILURE( "BasicTests%.lua(.+)Expected: true(.+)Actual: nil", function()
		EXPECT_TRUE( nil )
	end )
	EXPECT_NONFATAL_FAILURE( "BasicTests%.lua(.+)Expected: true(.+)Actual: false", function()
		EXPECT_TRUE( false )
	end )
end

function isFalse()
	EXPECT_FALSE( nil )
	ASSERT_FALSE( nil )
	EXPECT_FALSE( false )
	ASSERT_FALSE( false )
	EXPECT_FATAL_FAILURE( "BasicTests%.lua(.+)Expected: false(.+)Actual: 0", function()
		ASSERT_FALSE( 0 )
	end )
	EXPECT_FATAL_FAILURE( "BasicTests%.lua(.+)Expected: false(.+)Actual: \"false\"", function()
		ASSERT_FALSE( "false" )
	end )
	EXPECT_NONFATAL_FAILURE( "BasicTests%.lua(.+)Expected: false(.+)Actual: 0", function()
		EXPECT_FALSE( 0 )
	end )
	EXPECT_NONFATAL_FAILURE( "BasicTests%.lua(.+)Expected: false(.+)Actual: \"false\"", function()
		EXPECT_FALSE( "false" )
	end )
end

function isEqual()
	EXPECT_EQ( "foo", "foo" )
	ASSERT_EQ( "foo", "foo" )
	EXPECT_EQ( 3.1444444, 3.1444444 )
	ASSERT_EQ( 3.1444444, 3.1444444 )
	EXPECT_FATAL_FAILURE( 'BasicTests%.lua(.+)Expected: "foo"(.+)Actual: "bar"', function()
		ASSERT_EQ( "foo", "bar" )
	end )
	EXPECT_FATAL_FAILURE( 'BasicTests%.lua(.+)Expected: 3%.14444441(.+)Actual: 3%.14444442', function()
		ASSERT_EQ( 3.14444441, 3.14444442 )
	end )
	EXPECT_NONFATAL_FAILURE( 'BasicTests%.lua(.+)Expected: "foo"(.+)Actual: "bar"', function()
		EXPECT_EQ( "foo", "bar" )
	end )
	EXPECT_NONFATAL_FAILURE( 'BasicTests%.lua(.+)Expected: 3%.14444441(.+)Actual: 3%.14444442', function()
		EXPECT_EQ( 3.14444441, 3.14444442 )
	end )
end

function isNotEqual()
	EXPECT_NE( "foo", "bar" )
	ASSERT_NE( "foo", "bar" )
	EXPECT_NE( 3.14444441, 3.14444442 )
	ASSERT_NE( 3.14444441, 3.14444442 )
	EXPECT_FATAL_FAILURE( 'BasicTests%.lua(.+)Expected: "foo" ~= "foo", which is false', function()
		ASSERT_NE( "foo", "foo" )
	end )
	EXPECT_FATAL_FAILURE( 'BasicTests%.lua(.+)Expected: 3%.1444444 ~= 3%.1444444, which is false', function()
		ASSERT_NE( 3.1444444, 3.1444444 )
	end )
	EXPECT_NONFATAL_FAILURE( 'BasicTests%.lua(.+)Expected: "foo" ~= "foo", which is false', function()
		EXPECT_NE( "foo", "foo" )
	end )
	EXPECT_NONFATAL_FAILURE( 'BasicTests%.lua(.+)Expected: 3%.1444444 ~= 3%.1444444, which is false', function()
		EXPECT_NE( 3.1444444, 3.1444444 )
	end )
end
